### PR TITLE
* russian language. part 2

### PR DESCRIPTION
**Pull request by IManakhov**

### CODE REVIEW

**Comment by bzashev** [comment]
Thanks

**Comment by bzashev** [comment]
I have no idea why github is not adding you as contributor ... Any ideas?

**Comment by IManakhov** [comment]
No ideas! I am always using bitbucket.org for my project. So I am new in github)

**Comment by IManakhov** [comment]
I also wrote small console program for merging values that not included in {lang}.js from en.js. But it need small fixes for full using. I hope that I will put it with my next RU translation part)

**Comment by bzashev** [comment]
:) this will be perfect, it will help me too a lot, as I plan to maintain the bulgarian version (once I have a minute to spare)

**Pull request merged**
