### PR TITLE
* russian language. part 1

### PR DESCRIPTION
**Pull request by IManakhov**
it's first commit of translating to russian language

### CODE REVIEW

**Comment by bzashev** [comment]
:) Thanks. Merging asap :)

**Comment by bzashev** [comment]
Hey just change 	the translation variable name from translationsEN	to translationsRU. I already did that in the main source. Also I am pushing support (adding the option in the controller)

**Comment by IManakhov** [comment]
Hello! I have one question about WebVella ERP. Is it real to make reference
to subdivision for users and for another entities and set for users view
only items of entity that have reference to subdivision that have users?

2016-04-29 20:35 GMT+03:00 Bozhidar Zashev <notifications@github.com>:

**Comment by bzashev** [comment]
Hey,
can you redefine the question a little as I didn't understood it completely?

**Comment by IManakhov** [comment]
User have reference to Subdivision, Product have reference to subdivision.
Is it real to make view that show for user only products that have equal
subdivision?

2016-05-05 15:04 GMT+03:00 Bozhidar Zashev <notifications@github.com>:

**Comment by bzashev** [comment]
You have two alternatives:
1. To create a plugin with you own controller and feed the data you need to a view or a list
2. To create a couple list in view. In your have this should look something like 
a. you create a subdivision view with a list to its related products inside
b. you create a user view with the above view in it. 

The subviews are not very well tested after the latest restructuring so shoot a message if they give you trouble to fix

**Comment by IManakhov** [comment]
Thx very much, I will try it!

2016-05-05 16:21 GMT+03:00 Bozhidar Zashev <notifications@github.com>:

**Comment by bzashev** [comment]
You can see how a plugin is done in the SamplePlugin or Project plugins that are in the solution.
Frankly in most cases I prefer to take full control with my own controller and also my own html template, for the specific parts of the application.
You can see such a case in the projects -> my projects  list

**Comment by IManakhov** [comment]
I wanted to ask question about when you upload stable version. When I pull
last commit and I try to run solution I have many errors. I hope and
waiting that it will be soon =)

2016-05-05 16:59 GMT+03:00 Bozhidar Zashev <notifications@github.com>:

**Comment by bzashev** [comment]
Hey,
it shouldn't give you any errors if you fetch it now. Could you try and send me some errors to look at.

**Comment by bzashev** [comment]
In another issue, a guy point out that some of the packages are at rc2 and some at rc1 after the latest updates in the studio. Please check #83 if we are looking at the same problem. Also please open a new issue for questions as it is easier for me to track the problems this way.
thanks :) and again thanks for all the help.
(I checked the latest on the master and it should workout just fine accept the possible reference problem)

**Comment by bzashev** [comment]
I made a short fix for the reference error, could you pull and give it a try now?

**Comment by IManakhov** [comment]
Yeah, I pull new changes, all is ok! Thank you!

2016-05-06 14:40 GMT+03:00 Bozhidar Zashev <notifications@github.com>:

**Comment by bzashev** [comment]
Perfect. Thanks for the feedback. :). It was compiling here so we didn't knew there is a problem

**Pull request merged**
